# Generated by Django 4.1.7 on 2023-03-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_model',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
