# Generated by Django 4.1.1 on 2023-04-19 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_contact_model_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_property', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Property_Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='contact_model',
            options={'verbose_name_plural': 'Contacts Data'},
        ),
        migrations.AlterModelOptions(
            name='query_model',
            options={'verbose_name_plural': 'Customer Query'},
        ),
        migrations.AddField(
            model_name='query_model',
            name='reference',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.CreateModel(
            name='property_infomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_timeline', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('rera_number', models.CharField(max_length=100)),
                ('property_detail', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.property_category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.property_infomation')),
            ],
        ),
    ]
