# Generated by Django 4.1.1 on 2023-05-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_property_category_alter_contact_model_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_infomation',
            name='youtube_link',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
