# Generated by Django 4.1.1 on 2023-05-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_property_infomation_youtube_link'),
    ]

    operations = [
    ]
