# Generated by Django 4.1.1 on 2023-05-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20230513_1702'),
    ]

    operations = [
    ]
