# Generated by Django 4.1.1 on 2023-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_auto_20230513_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_infomation',
            name='amenities',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
