# Generated by Django 4.1.2 on 2023-06-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_property_infomation_amenities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=100)),
                ('Property_Type', models.CharField(max_length=100)),
                ('Property_Size', models.CharField(max_length=100)),
                ('Rate', models.CharField(max_length=100)),
            ],
        ),
    ]
