# Generated by Django 4.1.2 on 2023-06-28 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_property_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_model',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='query_model',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
